### ISSUE TITLE
Overlapping lookups in Info database

### ISSUE THREAD

**Issue by AceHack** [N3evin/AmiiboAPI#50] opened 2020-12-16 19:36 UTC
Amiibo
Super Smash Bros. (0000 - 0033)
Super Mario (0028)

Which one is correct?  is 0028 Super Mario or Super Smash Bros?

**Comment by AceHack** [comment] 2020-12-16 19:37
Amiibo
--
Name | Bytes
Super Smash Bros. | 0000 - 0033
023D
0251 - 0253
0258 - 025B
0362 - 0364
Super Mario | 0034 - 0039
00262 - 00263
0028
003C - 003D

**Comment by N3evin** [comment] 2020-12-17 02:10
> Amiibo
> Super Smash Bros. (0000 - 0033)
> Super Mario (0028)
> 
> Which one is correct? is 0028 Super Mario or Super Smash Bros?

Hi! Maybe I know which amiibo is causing the overlapping issue?

**Comment by N3evin** [comment] 2020-12-17 02:31
thank you! the issue is had been fixed in the google spreadsheet. However, for amiiboapi, we don't follow that section of the excel sheet, as that portion is for referencing only.

**Closed** 2020-12-18 13:03 UTC
Labels: bug
